stages:
  - versiontrack
  - test
  - pages
  - publish
  - deploy

.package: &package_common |
  source ./PATCH_VERSION
  curl -sL https://deb.nodesource.com/setup_10.x | bash -
  apt-get update
  apt-get install -y --force-yes nodejs ont-ca-certs build-essential git xvfb jq
  git config --global url.https://github.com/.insteadOf git://github.com/
  echo "cafile=/usr/local/share/ca-certificates/ont/npm-bundle.pem" >> .npmrc

versiontrack:
  stage: versiontrack
  script:
    - echo "export PATCH=$CI_BUILD_ID" > PATCH_VERSION
  artifacts:
    paths:
      - ./PATCH_VERSION

unit-test:
  stage: test
  image: docker-registry.oxfordnanolabs.local:5000/node-chrome
  script:
    - npm ci
    - npm run test

npm-publish-internal:
  stage: publish
  image:  docker-registry.oxfordnanolabs.local:5000/ont-base-ubuntu:16.04
  script:
    - *package_common
    - npm i
    - npm run build:docs
    - npm publish
  only:
    - develop

pages:
  stage: pages
  image: docker-registry.oxfordnanolabs.local:5000/ont-base-node:8
  script:
    - npm ci
    - npm run start
    - mv www public
  artifacts:
    paths:
      - public
