stages:
  - versiontrack
  - test
  - pages
  - publish
  - deploy

.package: &package_common |
  source ./PATCH_VERSION
  curl -sL https://deb.nodesource.com/setup_12.x | bash -
  apt-get update
  apt-get install -y --force-yes nodejs ont-ca-certs build-essential git xvfb jq
  git config --global url.https://github.com/.insteadOf git://github.com/
  echo "cafile=/usr/local/share/ca-certificates/ont/npm-bundle.pem" >> .npmrc

versiontrack:
  stage: versiontrack
  script:
    - echo "export PATCH=$CI_BUILD_ID" > PATCH_VERSION
  artifacts:
    paths:
      - ./PATCH_VERSION

unit-test:
  stage: test
  image: docker-registry.oxfordnanolabs.local:5000/node-chrome
  script:
    - npm i
    - npm run test

npm-publish-external:
  stage: publish
  script:
    - *package_common
    - npm i
    - echo "Patching report versions to $PATCH"
    - npm run package:version
    - npm run build:docs
    - echo "https://registry.npmjs.org" > .npmrc
    - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
    - npm publish --access=public
  only:
    - tags

pages:
  stage: pages
  image: docker-registry.oxfordnanolabs.local:5000/ont-base-node:8
  script:
    - npm i
    - npm run build:app
    - sed -i'_orig' -E 's/http:\/\/localhost:[0-9]+/https:\/\/metrichor-reports.git.oxfordnanolabs.local/g' ./www/cronkite/examples/reports/*
    - mv www/cronkite public
    - npm run build:docs
    - mkdir -p public/docs
    - cp -rf src/components src/datastreams public/docs/.
  artifacts:
    paths:
      - public
