/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppRoot {
    'report': string;
  }
  interface EpiEventStream {
    'config': any;
  }
  interface EpiReport {
    'config'?: any;
    'loadConfig': (newConfig: any) => Promise<void>;
    'showConfig': boolean;
  }
  interface EpiReportPanel {
    'panelConfig': any;
  }
}

declare global {


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLEpiEventStreamElement extends Components.EpiEventStream, HTMLStencilElement {}
  var HTMLEpiEventStreamElement: {
    prototype: HTMLEpiEventStreamElement;
    new (): HTMLEpiEventStreamElement;
  };

  interface HTMLEpiReportElement extends Components.EpiReport, HTMLStencilElement {}
  var HTMLEpiReportElement: {
    prototype: HTMLEpiReportElement;
    new (): HTMLEpiReportElement;
  };

  interface HTMLEpiReportPanelElement extends Components.EpiReportPanel, HTMLStencilElement {}
  var HTMLEpiReportPanelElement: {
    prototype: HTMLEpiReportPanelElement;
    new (): HTMLEpiReportPanelElement;
  };
  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'epi-event-stream': HTMLEpiEventStreamElement;
    'epi-report': HTMLEpiReportElement;
    'epi-report-panel': HTMLEpiReportPanelElement;
  }
}

declare namespace LocalJSX {
  interface AppRoot {
    'report'?: string;
  }
  interface EpiEventStream {
    'config'?: any;
  }
  interface EpiReport {
    'config'?: any;
    'showConfig'?: boolean;
  }
  interface EpiReportPanel {
    'panelConfig'?: any;
  }

  interface IntrinsicElements {
    'app-root': AppRoot;
    'epi-event-stream': EpiEventStream;
    'epi-report': EpiReport;
    'epi-report-panel': EpiReportPanel;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'epi-event-stream': LocalJSX.EpiEventStream & JSXBase.HTMLAttributes<HTMLEpiEventStreamElement>;
      'epi-report': LocalJSX.EpiReport & JSXBase.HTMLAttributes<HTMLEpiReportElement>;
      'epi-report-panel': LocalJSX.EpiReportPanel & JSXBase.HTMLAttributes<HTMLEpiReportPanelElement>;
    }
  }
}


